FWAPI-160: firewaller refusing to start with "TypeError: Property '_setOldIPF' of object #<Object> is not a function"
This reverts ipf.js to the version as of commit a10d1eb, and
re-introduces fw._setOldIPF().